config/routes.rb
Wh::Application.routes.draw do 

  # Main routes

  root :to => "public#index"
  match "/about" => "public#about"
  match "/contact" => "public#contact"

  # Carriage routes

  match "carriages" => "carriages#create", :as => "carriage", :via => :post
  match "carriages" => "carriages#index", :as => "carriage_index"
  match "carriages/new/:q" => "carriages#new", :as => "carriage_new"
  match "carriages/new" => "carriages#new", :as => "carriage_new"
  match "carriages/scan/:q" => "carriages#barcode", :as => "carriage_scan"
  match "carriages/scan" => "carriages#barcode", :as => "carriage_scan"
  match "carriages/view/:serial" => "carriages#view", :as => "carriage_show"
  match "carriages/edit/:serial" => "carriages#edit", :as => "carriage_edit"
  match "carriages/view/:warehouse_point" => "carriages#position", :as => "carriage_position"
  match "carriages/:serial" => "carriages#destroy", :as => "carriage_delete", :via => [:get, :delete]
  match "carriages/:serial" => "carriages#update", :as => "carriage_update", :via => :put

  # User routes

  match "users" => "users#index", :as => "user_index"
  match "login" => "users#login", :as => "login", :via => [:get, :post]
  match "register" => "users#register"
  match "users/create", :as => "users", :via => [:post, :get]
  match "logout" => "users#destroy"

  #Surveyors routes, sub inventory & orders routes

  match ":department/mats" => "mats#index", :as => "mats", via: [:get]
  match ":department/mats/new" => "mats#new", :as => "new_mat", via: [:get]
  match ":department/mats/new" => "mats#create", via: [:post]
  match ":department/mats/:id/edit" => "mats#edit", :as => "edit_mat", via: [:get]
  match "mats/:id" => "mats#show", :as => "mat", via: [:get]
  match ":department/mats/:id/edit" => "mats#update",:as => "mat", via: [:put]
  match ":department/mat/:id" => "mats#destroy", :as => "mats_del", via: [:get, :destroy]

  # barcode resources

  match "barcodes" => "barcodes#index"
  match "scan/update/:id" => "barcodes#update"
  match "scan/receive/:id" => "barcodes#receive"

  # JS session update timer route

  get "application/update_timer"

  # Seats resources
  # TODO: Break up into unique routes

  resources :seats
  
end

 # mats      GET        /mats(.:format)                            mats#index
 #           POST       /mats(.:format)                            mats#create
 # new_mat   GET        /mats/new(.:format)                        mats#new
 # edit_mat  GET        /mats/:id/edit(.:format)                   mats#edit
 # mat       GET        /mats/:id(.:format)                        mats#show
 #           PUT        /mats/:id(.:format)                        mats#update
 #           DELETE     /mats/:id(.:format)                        mats#destroy

app/models/seat.rb
class Seat < ActiveRecord::Base
end

app/controllers/seats_controller.rb
class SeatsController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
  end

  def update

  end

  def destroy
  end

end

app/helpers/seats_helper.rb
module SeatsHelper
end

app/views/seats/_form.html.erb
<%= form_for(@seat) do |f| %>
  <% if @seat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@seat.errors.count, "error") %> prohibited this seat from being saved:</h2>

      <ul>
      <% @seat.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br />
    <%= f.text_field :id %>
  </div>
  <div class="field">
    <%= f.label :serial %><br />
    <%= f.text_field :serial %>
  </div>
  <div class="field">
    <%= f.label :model %><br />
    <%= f.text_field :model %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/seats/edit.html.erb
<h1>Editing seat</h1>

<%= render 'form' %>

<%= link_to 'Show', @seat %> |
<%= link_to 'Back', seats_path %>

app/views/seats/index.html.erb
<h1>Listing seats</h1>

<table>
  <tr>
    <th>Id</th>
    <th>Serial</th>
    <th>Model</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @seats.each do |seat| %>
  <tr>
    <td><%= seat.id %></td>
    <td><%= seat.serial %></td>
    <td><%= seat.model %></td>
    <td><%= link_to 'Show', seat %></td>
    <td><%= link_to 'Edit', edit_seat_path(seat) %></td>
    <td><%= link_to 'Destroy', seat, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Seat', new_seat_path %>

app/views/seats/new.html.erb
<h1>New seat</h1>

<%= render 'form' %>

<%= link_to 'Back', seats_path %>

app/views/seats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @seat.id %>
</p>

<p>
  <b>Serial:</b>
  <%= @seat.serial %>
</p>

<p>
  <b>Model:</b>
  <%= @seat.model %>
</p>


<%= link_to 'Edit', edit_seat_path(@seat) %> |
<%= link_to 'Back', seats_path %>