config/routes.rb
Wh::Application.routes.draw do 

  # Main routes

  root :to => "public#index"
  match "/about" => "public#about"
  match "/contact" => "public#contact"

  # Carriage routes

  match "carriages" => "carriages#create", :as => "carriage", :via => :post
  match "carriages" => "carriages#index", :as => "carriage_index"
  match "carriages/new/:q" => "carriages#new", :as => "carriage_new"
  match "carriages/new" => "carriages#new", :as => "carriage_new"
  match "carriages/scan/:q" => "carriages#barcode", :as => "carriage_scan"
  match "carriages/scan" => "carriages#barcode", :as => "carriage_scan"
  match "carriages/view/:serial" => "carriages#view", :as => "carriage_show"
  match "carriages/edit/:serial" => "carriages#edit", :as => "carriage_edit"
  match "carriages/view/:warehouse_point" => "carriages#position", :as => "carriage_position"
  match "carriages/:serial" => "carriages#destroy", :as => "carriage_delete", :via => [:get, :delete]
  match "carriages/:serial" => "carriages#update", :as => "carriage_update", :via => :put

  # User routes

  match "users" => "users#index", :as => "user_index"
  match "login" => "users#login", :as => "login", :via => [:get, :post]
  match "register" => "users#register"
  match "users/create", :as => "users", :via => [:post, :get]
  match "logout" => "users#destroy"

  #Surveyors routes, sub inventory & orders routes

  match ":department/mats" => "mats#index", :as => "mats", via: [:get]
  match ":department/mats/new" => "mats#new", :as => "new_mat", via: [:get]
  match ":department/mats/new" => "mats#create", via: [:post]
  match ":department/mats/:id/edit" => "mats#edit", :as => "edit_mat", via: [:get]
  match "mats/:id" => "mats#show", :as => "mat", via: [:get]
  match ":department/mats/:id/edit" => "mats#update",:as => "mat", via: [:put]
  match ":department/mat/:id" => "mats#destroy", :as => "mats_del", via: [:get, :destroy]

  # barcode resources

  match "barcodes" => "barcodes#index"
  match "scan/update/:id" => "barcodes#update"
  match "scan/receive/:id" => "barcodes#receive"

  # JS session update timer route

  get "application/update_timer"

  # Seats resources
  # TODO: Break up into unique routes

  resources :seats
  
end

 # mats      GET        /mats(.:format)                            mats#index
 #           POST       /mats(.:format)                            mats#create
 # new_mat   GET        /mats/new(.:format)                        mats#new
 # edit_mat  GET        /mats/:id/edit(.:format)                   mats#edit
 # mat       GET        /mats/:id(.:format)                        mats#show
 #           PUT        /mats/:id(.:format)                        mats#update
 #           DELETE     /mats/:id(.:format)                        mats#destroy

app/models/carriage.rb
class Carriage < ActiveRecord::Base

	attr_protected :id

  	validates :serial, :model, :orientation, :status, :stype, :presence => true
  	validates :serial, :uniqueness => true, :numericality => true, :length => { :maximum => 12 }
  
end

app/controllers/carriages_controller.rb
class CarriagesController < ApplicationController
  before_filter :find_carriage, :only => %w[view edit update destroy]
  before_filter :check_admin_and_logged_in, :only => %w[index bardcode position new view]

  def index 
    @carriages = Carriage.all
    @carriages_position = Carriage.order("warehouse_point ASC").map(&:warehouse_point).uniq 
  end
  
  def barcode
    @page_title = "Scan"
    @barcode = params[:q].split('-').reverse.delete_at(1) if !params[:q].blank?
    @uniq = Carriage.find_by_serial(@barcode)
  end
  
  def position
    @carriage = Carriage.find_by_warehouse_point(:warehouse_point)
  end

  def new
    @page_title = "Create"
    @carriage = Carriage.new
    @barcode = params[:q].split('-').reverse.delete_at(1) if !params[:q].blank?
  end

  def create
    @carriage = Carriage.new(params[:carriage])

    if request.post?
      if @carriage.save
        redirect_to carriage_show_path(@carriage.serial), :notice => "Carriage succesfully created"
      else
        render :action => :new
      end
    end
  end
  
  def view
    @page_title = "View ##{@carriage.serial}"
  end

  def edit
    @page_title = ":edit => {:serial => #{@carriage.serial}}"
  end

  def update
    if @carriage.update_attributes(params[:carriage])
      redirect_to carriage_show_path(@carriage.serial), :notice => 'Carriage was successfully updated.'
    else
      render :action => :edit
    end
  end

  def destroy
    @carriage.destroy 
    redirect_to carriage_path, :head => :ok
  end

  protected

  def find_carriage
    @carriage = Carriage.find_by_serial(params[:serial])
  end 

  def check_admin_and_logged_in
    @admin = @logged_in = true
  end    
end

app/helpers/carriages_helper.rb
module CarriagesHelper 
  def carriage_model
    return nil if params[:q].nil?
    m = params[:q].to(3)
    case m
      when "1101" then "A120"
      when "1104" then "B80"
    end 
  end
  
  def carriage_orientation
    return nil if params[:q].nil?
    m = params[:q].to(5).reverse.to(0)
    case m
      when "1" then "LH"
      when "2" then "RH"
    end 
  end

  def carriage_type
    return "Indoor;Outdoor;Curve;Perch".split(";")
  end

  def carriage_status
    return "In_Repair;Awaiting_Inspection;New;Scrap;Quarantine".split(";")
  end

  def carriage_nil?
    return true if @barcode.to_s.length > 12 || !params[:q].blank? && @barcode.blank? && params[:q].to_s.length <= 12
  end

end

app/views/carriages/_form.html.erb
<%= form_for @carriage, :url => carriage_path, :html => { :class => "form-horizontal" } do |f| %>
  
  <% if @carriage.errors.any? %>
    <div class="span7 pull-right">
      <%= show_msg "#{pluralize(@carriage.errors.count, "error")} found", "info" %>
      <ul>
      <% @carriage.errors.full_messages.each do |error_message| %>
        <%= content_tag :li, error_message %>
      <% end %>
      </ul>
    </div>
  <% end %>
    
  <div class="span4 pull-left">
    <div class="control-group">
      <%= f.label :Serial, :class => "control-label", :for => "carriages_serial" %>
      <div class="controls">
        <%= f.text_field :serial, :value => @barcode, :placeholder => "Serial" %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :Model, :class => "control-label", :for => "carriages_model" %>
      <div class="controls">
        <%= f.text_field :model, :value => carriage_model, :placeholder => "Model" %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :Orientation, :class => "control-label", :for => "carriages_orientation" %>
      <div class="controls">
        <%= f.text_field :orientation, :value => carriage_orientation, :placeholder => "Orientation" %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :Motor, :class => "control-label", :for => "carriages_motor" %>
      <div class="controls">
        <%= f.text_field :motor, :placeholder => "Motor #", :maxlength => 6 %>
      </div>
    </div>
      
    <div class="control-group">
      <%= f.label :PCB, :class => "control-label", :for => "carriages_pcb" %>
      <div class="controls">
        <%= f.text_field :pcb, :maxlength => 6, :placeholder => "PCB #" %>
      </div>
    </div>
      
    <div class="control-group">
      <%= f.label :Order_No, :class => "control-label", :for => "carriages_orderno" %>
      <div class="controls">
        <%= f.text_field :orderno, :maxlength => 6, :placeholder => "Order #" %>
      </div>
    </div>
      
    <div class="control-group">
      <%= f.label :Warehouse_Point, :class => "control-label", :for => "carriages_warehouse_point" %>
      <div class="controls">
        <%= f.text_field :warehouse_point, :placeholder => "Warehouse point" %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :Type, :class => "control-label", :for => "carriages_type" %>
     <div class="controls">
        <%= select :carriage, :stype, carriage_type.each { |t| [t.humanize, t] } %> 
      </div>
    </div>

    <div class="control-group">
      <%= f.label :Status, :class => "control-label", :for => "carriages_status" %>
      <div class="controls">
        <%= select :carriage, :status, carriage_status.each { |t| [t.humanize, t] } %> 
      </div>
    </div>

    <%= f.submit :Add, :class => "pull-right" %>
  
  </div>
  
<% end %>

app/views/carriages/barcode.html.erb
<% if carriage_nil? %>
	<%= show_msg "Invalid Barcode ##{params[:q]}", "error" %>
<% else %>

	<h3 class="no-bold legend">Barcode Scanner</h3>

	<p>
	  <%= link_to "Scan", "http://zxing.appspot.com/scan?ret=http://warehouseapp.net/carriages/scan/{CODE}&SCAN_FORMATS=CODE_128", :class => "btn btn-block" %>
	</p>

	<% if @uniq %>
	  <%= show_msg "#{content_tag(:b, @uniq.serial)} already exists, what do?", "success" %>
	  <%= link_to "Edit", carriage_edit_path(@uniq.id), :class => "btn btn-block btn-primary" %><br>
	  <%= link_to 'Destroy', carriage_delete_path(@barcode), :method => :delete, :class => "btn btn-block btn-primary" %>
	<% elsif !@uniq && @barcode %>
	  <%= show_msg "What would you like to do with #{content_tag(:b, @barcode)}", "success" %>
	  <%= link_to "Add", carriage_new_path + "/" + params[:q], :class => "btn btn-block btn-primary" %><br>
	<% end %>

	<p class="well">This feature allows you to scan and retrieve information relating 
		to a barcode. Currently this feature only allows barcodes
		using the PLAIN TEXT/CODE_128 format for increased performance 
		during the development phase. </p>

<% end %>

app/views/carriages/edit.html.erb
<h3 class="no-bold page-header">
  Editing <%= @carriage.serial %> (<%= link_to 'Back', carriage_show_path(@carriage.serial) %>)
</h3>

<%= form_for @carriage, :url => carriage_update_path do |f| %>
    <table class="table table-fluid">
      <thead>
        <tr>
          <th>#</th>
          <th>Model</th>
          <th>Type</th>
          <th>Orientation</th>
          <th>Motor</th>
          <th>PCB</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><%= @carriage.id %></td>
          <td><%= f.text_field :model, :class => "input-small" %></td>
          <td><%= select :carriage, :stype, carriage_type.each { |t| [t.humanize, t] }, {:include_blank => "Carriage type"}, {:class => "input-small"} %></td>
          <td><%= f.text_field :orientation, :class => "input-small" %></td>
          <td><%= f.text_field :motor, :class => "input-small" %></td>
          <td><%= f.text_field :pcb, :class => "input-small" %></td>
        </tr>
      </tbody>
      <thead>
        <tr>
          <th>Status</th>
          <th>Order #</th>
          <th>Created at</th>
          <th>Updated at</th>
          <th>Warehouse position</th>
          <th>Serial</th>
        </tr>
      </thead>
      <tbody>
      <tr>
        <td><%= select :carriage, :status, carriage_status.each { |t| [t.humanize, t] }, {:include_blank => "Carriage type"}, {:class => "input-small"} %></td>
        <td><%= f.text_field :orderno, :class => "input-small" %></td>
        <td><%= f.text_field :created_at, :class => "input-small" %></td>
        <td><%= f.text_field :updated_at, :class => "input-small" %></td>
        <td><%= f.text_field :warehouse_point, :class => "input-small" %></td>
        <td><%= f.text_field :serial, :class => "input-small" %></td>
      </tr>
      </tbody>
    </table>
    <%= f.submit :Update, :class => "clearfix btn btn-primary"  %>
<% end %>

app/views/carriages/index.html.erb
<% return show_msg "No carriages found. #{link_to 'Create', carriage_new_path, :class => "pull-right"}", "warning" if @carriages.blank? && @carriages_position.blank? %>

<p class="page-header">
  <%= link_to "Create", carriage_new_path, :class => "btn btn-primary pull-left" %>
  <%= link_to "Scan", carriage_scan_path, :class => "btn btn-primary pull-left" %>
</p>

<div class="span11 pull-left">
  <% @carriages_position.each do |carriage_position| %>
    <%= content_tag :div, :id => carriage_position, :class => "span3 clearfix" do %>
      <h3 class="muted no-bold legend">
        <%= carriage_position.capitalize %>
      </h3>
      <% @carriages.each do |carriage| %>
        <% if carriage_position == carriage.warehouse_point %>
          <div class="carriage_icon">
            <%= link_to carriage.model, carriage_show_path(carriage.serial) %>
          </div>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/carriages/new.html.erb
<h3 class="no-bold legend">Add carriage</h3>

  <%= render 'form' %>

app/views/carriages/position.html.erb
<div id="carriage_container">
  <% @carriage.each do |c| %>

    <div class="carriage_icon"><%= c.model %></div>
  
  <% end %>
</div>

app/views/carriages/view.html.erb
<% return show_msg("No Carriage found with ##{params[:serial]}", "error") if @carriage.nil? %>

<h3 class="no-bold pull-left page-header">
  <%= @carriage.serial %>
</h3>
<p class="pull-right">
  <%= link_to 'Edit', carriage_edit_path(@carriage.serial), :class => "btn btn-primary page-header" %> 
  <%= link_to 'Destroy', carriage_delete_path(@carriage.serial), :method => :delete, :class => "btn btn-primary page-header" %>
</p>
<table class="table table-fluid">
  <thead>
    <tr>
      <th>#</th>
      <th>Model</th>
      <th>Type</th>
      <th>Orientation</th>
      <th>Motor</th>
      <th>PCB</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @carriage.id %></td>
      <td><%= @carriage.model %></td>
      <td><%= @carriage.stype.humanize %></td>
      <td><%= @carriage.orientation %></td>
      <td><%= @carriage.motor %></td>
      <td><%= @carriage.pcb %></td>
    </tr>
  </tbody>
  <thead>
    <tr>
      <th>Status</th>
      <th>Order #</th>
      <th>Created at</th>
      <th>Updated at</th>
      <th>Warehouse position</th>
      <th>Serial</th>
    </tr>
  </thead>
  <tbody>
  <tr>
    <td><%= @carriage.status.humanize %></td>
    <td><%= @carriage.orderno %></td>
    <td><%= @carriage.created_at %></td>
    <td><%= @carriage.updated_at %></td>
    <td><%= @carriage.warehouse_point.capitalize %></td>
    <td><%= @carriage.serial %></td>
  </tr>
  </tbody>
</table>