config/routes.rb
Wh::Application.routes.draw do 

  # Main routes

  root :to => "public#index"
  match "/about" => "public#about"
  match "/contact" => "public#contact"

  # Carriage routes

  match "carriages" => "carriages#create", :as => "carriage", :via => :post
  match "carriages" => "carriages#index", :as => "carriage_index"
  match "carriages/new/:q" => "carriages#new", :as => "carriage_new"
  match "carriages/new" => "carriages#new", :as => "carriage_new"
  match "carriages/scan/:q" => "carriages#barcode", :as => "carriage_scan"
  match "carriages/scan" => "carriages#barcode", :as => "carriage_scan"
  match "carriages/view/:serial" => "carriages#view", :as => "carriage_show"
  match "carriages/edit/:serial" => "carriages#edit", :as => "carriage_edit"
  match "carriages/view/:warehouse_point" => "carriages#position", :as => "carriage_position"
  match "carriages/:serial" => "carriages#destroy", :as => "carriage_delete", :via => [:get, :delete]
  match "carriages/:serial" => "carriages#update", :as => "carriage_update", :via => :put

  # User routes

  match "users" => "users#index", :as => "user_index"
  match "login" => "users#login", :as => "login", :via => [:get, :post]
  match "register" => "users#register"
  match "users/create", :as => "users", :via => [:post, :get]
  match "logout" => "users#destroy"

  #Surveyors routes, sub inventory & orders routes

  match ":department/mats" => "mats#index", :as => "mats", via: [:get]
  match ":department/mats/new" => "mats#new", :as => "new_mat", via: [:get]
  match ":department/mats/new" => "mats#create", via: [:post]
  match ":department/mats/:id/edit" => "mats#edit", :as => "edit_mat", via: [:get]
  match "mats/:id" => "mats#show", :as => "mat", via: [:get]
  match ":department/mats/:id/edit" => "mats#update",:as => "mat", via: [:put]
  match ":department/mat/:id" => "mats#destroy", :as => "mats_del", via: [:get, :destroy]

  # barcode resources

  match "barcodes" => "barcodes#index"
  match "scan/update/:id" => "barcodes#update"
  match "scan/receive/:id" => "barcodes#receive"

  # JS session update timer route

  get "application/update_timer"

  # Seats resources
  # TODO: Break up into unique routes

  resources :seats
  
end

 # mats      GET        /mats(.:format)                            mats#index
 #           POST       /mats(.:format)                            mats#create
 # new_mat   GET        /mats/new(.:format)                        mats#new
 # edit_mat  GET        /mats/:id/edit(.:format)                   mats#edit
 # mat       GET        /mats/:id(.:format)                        mats#show
 #           PUT        /mats/:id(.:format)                        mats#update
 #           DELETE     /mats/:id(.:format)                        mats#destroy

app/models/mat.rb
class Mat < ActiveRecord::Base
  attr_accessible :amount_left, :amount_per_box, :artwork, :name, 
				  :wh_position, :department
  validates :amount_left, :amount_per_box, :name, :presence => true

  	def self.check_departments(dept_var, dept_required)
	    objArray = []
	    @cur_dept = dept_required
	    dept_var.each do |t|
	      split_dept = t.department.split(',')
	        if split_dept.include?(dept_required) == true then
	            if objArray == nil then
	            	objArray.push t
	            else
	          		objArray << t
	            end
	        end
	    end
		objArray.to_a
	end

	def self.arr2str_checkboxes(dept_arr)
		objArray = []
		return nil if dept_arr.blank?
		dept_arr.each do |key, department|
	  		if objArray == nil then
				objArray = [].push department.downcase
			else
				objArray << department.downcase
			end
		end
		objArray * ","
	end

	protected
	# TODO: research variable permissions^
	def self.create_arr(data)  	
		if objArray == nil then
			objArray = [].push data
		else
			objArray << data
		end
	end
end

app/controllers/mats_controller.rb
class MatsController < ApplicationController
   before_filter :check_admin_and_logged_in, :only => %w[new edit]
  # GET /mats
  # GET /mats.json
  def index
    @mats = Mat.check_departments(Mat.all, params[:department])
  end

  # GET /mats/1
  # GET /mats/1.json
  def show
    @mat = Mat.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @mat }
    end
  end

  # GET /mats/new
  # GET /mats/new.json
  def new
    @mat = Mat.new

    render :layout => false
  end

  # GET /mats/1/edit
  def edit
    @mat = Mat.find(params[:id])
    render :layout => false
  end

  # POST /mats
  # POST /mats.json
  def create
    @mat = Mat.new(params[:mat])
    @mat.department = Mat.arr2str_checkboxes(params[:chk])

    respond_to do |format|
      if @mat.save
        format.html { redirect_to request.referer, notice: 'Materials successfully created.' }
        format.json { render json: @mat, status: :created, location: @mat }
      else
        format.html { render action: "new" }
        format.json { render json: @mat.errors, status: :unprocessable_entity }
      end 
    end
  end

  # PUT /mats/1
  # PUT /mats/1.json
  def update
    @mat = Mat.find(params[:id]) 
    dept = params[:chk]
    logger.debug dept
    if dept.nil?
      params[:mat][:department] = 'obsolete'
    else
      params[:mat][:department] = Mat.arr2str_checkboxes(params[:chk])
    end

    respond_to do |format|
      if @mat.update_attributes(params[:mat])
        format.html { redirect_to request.referer, notice: 'Mat was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @mat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mats/1
  # DELETE /mats/1.json
  def destroy
    @mat = Mat.find(params[:id])
    @mat.destroy

    respond_to do |format|
      format.html { redirect_to mats_url }
      format.json { head :no_content }
    end
  end

  protected 

  def check_admin_and_logged_in
    @admin = @logged_in = true
  end 
end

app/helpers/mats_helper.rb
module MatsHelper
	def is_stock_low(stock_level)
		if stock_level <= 1
			return " error"
		end
	end

	def valid_department
		return ["installers", "surveyors", "dealers", "partners", "obsolete"].include? params[:department]
	end

	def active_tab(department)
		if params[:department] == department 
		  return 'class="active"'.html_safe
		end
	end

	def format_date(date)
		d = date
		return d.strftime("%m/%d/%Y @ %I:%M%p")
	end

	def active_departments(department)
		if @mat.department.nil?
			return "checked" if params[:department] == department
		else
			dept_arr = @mat.department.split(',')
			dept_arr.each do |dept|
				return "checked" if dept == department
			end
		end
	end	
end

app/views/mats/_form.html.erb
	<% if @thisistrue %>
		<div>youwinNOTHING</abc>
	<% end -%>

	<%= form_for @mat, url: { :department => params[:department] } do |f| %>

	<div class="">
		<table id="edit" class="table">
		<%= content_tag :div, class: "form-inline form_uni", role: "form", :data => { id: @mat.id } do %>
		<td>
			<div class="form-group">
				<label class="control-label">Name:</label>
				<div>
					<%= f.text_field :name, class: "form-control input-sm", placeholder: @mat.artwork, required: true, autofocus: true %>
				</div>
			</div>
		</td>
		<td>
			<div class="form-group">
				<label class="control-label">Artwork:</label>
				<div>
					<%= f.text_field :artwork, class: "form-control input-sm", placeholder: @mat.artwork %>
				</div>
			</div>
		</td>
		<td>
			<div class="form-group">
				<label class="control-label">Amount Left:</label>
				<div>
					<%= f.number_field :amount_left, class: "form-control input-sm", placeholder: @mat.amount_left, required: true  %>
				</div>
			</div>
		</td>
		<td>
			<div class="form-group">
				<label class="control-label">Amount Per Box:</label>
				<div>
					<%= f.number_field :amount_per_box, class: "form-control input-sm", placeholder: @mat.amount_per_box, required: true  %>
				</div>
			</div>
		</td>
		<td>
			<div class="form-group">
				<label class="control-label">Location:</label>
				<div>
					<%= f.text_field :wh_position, class: "form-control input-sm", placeholder: @mat.wh_position %>
				</div>
			</div>
		</td>
		<div class="form-group pull-left well-sm">
			<label class="checkbox-inline" for="chkDealers">
            	<input type="checkbox" name="chk[0]" id="chkDealers" value="Dealers" <%= active_departments("dealers") %>>
            	Dealers
        	</label> 
        </div>
        <div class="form-group pull-left well-sm">
        	<label class="checkbox-inline" for="chkInstallers">
            	<input type="checkbox" name="chk[1]" id="chkInstallers" value="Installers" <%= active_departments("installers") %>>
            	Installers
        	</label> 
        </div>
        <div class="form-group pull-left well-sm">
        	<label class="checkbox-inline" for="chkPartners">
            	<input type="checkbox" name="chk[2]" id="chkPartners" value="Partners" <%= active_departments("partners") %>>
            	Partners
        	</label> 
        </div>
        <div class="form-group pull-left well-sm">
        	<label class="checkbox-inline" for="chkSurveyors">
            	<input type="checkbox" name="chk[3]" id="chkSurveyors" value="Surveyors" <%= active_departments("surveyors") %>>
            	Surveyors
        	</label> 
        </div>
		<% end -%>
	</table>
	</div> 
	<div class="form-group hidden">
		<%= f.submit class: "btn btn-sm btn-success" %>
	</div>
	<% end %>

app/views/mats/edit.html.erb
<%= render :partial => 'form' %>

app/views/mats/index.html.erb
<% return show_msg "Invalid department parameter given.", "error" if not valid_department %>

<% if flash[:notice] %>
  <div class="well-sm"><%= show_flash flash[:notice], "success" %></div>
<% end -%>

<div id="form"></div>

<div class="well-sm pull-right">
  <%= link_to 'Add Material', '#', class: "btn-sm btn-primary new_mat", remote: true %>
</div>

<div id="">
  <div class="">
    <table class="table sticky-header">
      <thead style="background-color: #FFF">
        <tr>
          <th>Name</th>
          <th class="hidden-phone">Artwork</th>
          <th>Amount left (Boxes)</th>
          <th class="hidden-phone">Amount per box</th>
          <th class="hidden-phone">Total Amount</th>
          <th>Warehouse Position</th>
          <th>Last Updated</th>
          <% if is_admin? %>
            <th>Delete</th>
          <% end -%>
        </tr>
      </thead>
      <% @mats.each do |m| %>
        <tbody>
          <tr class="m<%= m.id %><%= is_stock_low m.amount_left %>">
            <td><%= m.name %> </td>
            <td class="hidden-phone"><%= m.artwork %></td>
            <td><%= m.amount_left %></td>
            <td class="hidden-phone"><%= m.amount_per_box%></td>
            <td class="hidden-phone"><%= m.amount_left * m.amount_per_box %></td>
            <td><%= m.wh_position %></td>
            <td><%= format_date m.updated_at %></td>
            <% if is_admin? %>
            <td class="<%= m.id %>"><%= link_to 'Update', '#', class: "btn-link edit_mat", id: m.id, remote: true %></td>
              <td><%= link_to :Destroy, mats_del_path(id: m.id), data: { id: m.id } %></td>
            <% end -%>
          </tr>
        </tbody>
      <% end -%>
    </table>
   </div>
 </div>
<div id="add_material">
</div>

app/views/mats/new.html.erb
<%= render :partial => 'form' %>

app/views/mats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @mat.name %>
</p>

<p>
  <b>Artwork:</b>
  <%= @mat.artwork %>
</p>

<p>
  <b>Amount left:</b>
  <%= @mat.amount_left %>
</p>

<p>
  <b>Amount per box:</b>
  <%= @mat.amount_per_box %>
</p>

<p>
  <b>Wh position:</b>
  <%= @mat.wh_position %>
</p>


<%= link_to 'Edit', edit_mat_path(@mat) %> |
<%= link_to 'Back', mats_path %>