config/routes.rb
Wh::Application.routes.draw do 

  # Main routes

  root :to => "public#index"
  match "/about" => "public#about"
  match "/contact" => "public#contact"

  # Carriage routes

  match "carriages" => "carriages#create", :as => "carriage", :via => :post
  match "carriages" => "carriages#index", :as => "carriage_index"
  match "carriages/new/:q" => "carriages#new", :as => "carriage_new"
  match "carriages/new" => "carriages#new", :as => "carriage_new"
  match "carriages/scan/:q" => "carriages#barcode", :as => "carriage_scan"
  match "carriages/scan" => "carriages#barcode", :as => "carriage_scan"
  match "carriages/view/:serial" => "carriages#view", :as => "carriage_show"
  match "carriages/edit/:serial" => "carriages#edit", :as => "carriage_edit"
  match "carriages/view/:warehouse_point" => "carriages#position", :as => "carriage_position"
  match "carriages/:serial" => "carriages#destroy", :as => "carriage_delete", :via => [:get, :delete]
  match "carriages/:serial" => "carriages#update", :as => "carriage_update", :via => :put

  # User routes

  match "users" => "users#index", :as => "user_index"
  match "login" => "users#login", :as => "login", :via => [:get, :post]
  match "register" => "users#register"
  match "users/create", :as => "users", :via => [:post, :get]
  match "logout" => "users#destroy"

  #Surveyors routes, sub inventory & orders routes

  match ":department/mats" => "mats#index", :as => "mats", via: [:get]
  match ":department/mats/new" => "mats#new", :as => "new_mat", via: [:get]
  match ":department/mats/new" => "mats#create", via: [:post]
  match ":department/mats/:id/edit" => "mats#edit", :as => "edit_mat", via: [:get]
  match "mats/:id" => "mats#show", :as => "mat", via: [:get]
  match ":department/mats/:id/edit" => "mats#update",:as => "mat", via: [:put]
  match ":department/mat/:id" => "mats#destroy", :as => "mats_del", via: [:get, :destroy]

  # barcode resources

  match "barcodes" => "barcodes#index"
  match "scan/update/:id" => "barcodes#update"
  match "scan/receive/:id" => "barcodes#receive"

  # JS session update timer route

  get "application/update_timer"

  # Seats resources
  # TODO: Break up into unique routes

  resources :seats
  
end

 # mats      GET        /mats(.:format)                            mats#index
 #           POST       /mats(.:format)                            mats#create
 # new_mat   GET        /mats/new(.:format)                        mats#new
 # edit_mat  GET        /mats/:id/edit(.:format)                   mats#edit
 # mat       GET        /mats/:id(.:format)                        mats#show
 #           PUT        /mats/:id(.:format)                        mats#update
 #           DELETE     /mats/:id(.:format)                        mats#destroy

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><% if @page_title %><%= create_page_title %><% else %>WarehouseApp<% end %></title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= favicon_link_tag %>
  <%= stylesheet_link_tag 'application' %>
  <%= csrf_meta_tag %>
</head>
<body>

   <div class="navbar navbar-default navbar-static-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "WarehouseApp", user_index_path, :class => "navbar-brand" %>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to 'Home', user_index_path %></li>
              <% if is_logged_in? %>
                <li <%= active_tab("dealers") %>><%= link_to "Dealers", mats_path(:dealers) %></li>
                <li <%= active_tab("installers") %>><%= link_to "Installers", mats_path(:installers) %></li>
                <li <%= active_tab("partners") %>><%= link_to "Partners", mats_path(:partners) %></li>
                <li <%= active_tab("surveyors") %>><%= link_to "Surveyors", mats_path(:surveyors) %></li>            
              <% end %>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if is_logged_in? %>
              <li><%= link_to 'Logout', logout_path %> </li>
            <% else %>
              <li><%= link_to 'Login', login_path %></li>
              <li><%= link_to 'Register', register_path %></li>
            <% end %>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>
  
  <div class="subnav container">   
    <div class="row-fluid">
      <% if !is_logged_in? && @logged_in %>
        <%= show_msg login_required_text, "warning" %>
      <% elsif !is_admin? && @admin %>
        <%= show_msg admin_required_text, "warning" %>
      <% else -%>
        <%= yield %>
      <% end -%>
    </div>
  </div>

  <div class="container">
    <div class="pull-right muted">
      &copy; <%= Time.now.year %> WarehouseApp.net / <%= link_to "About", about_path %> / <%= link_to "Contact", contact_path %> 
    </div>
  </div>
</body>
</html>
<%= javascript_include_tag '//ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js', 'application' %>